/** This file is autogenerated */

import { ModuleWithProviders }  from "@angular/core";
import { Routes, RouterModule } from "@angular/router";
import { Main } from "./Component/Main/Main/Main";
import { DemoDemo0 } from "./Component/demo/demo0/demo0";
import { DemoIndex } from "./Component/demo/index/index";
const appRoutes: Routes = [
	{
		path: "Main",
		component : Main
	},
	{
		path: "DemoDemo0",
		component : DemoDemo0
	},
	{
		path: "DemoIndex",
		component : DemoIndex
	},
	{
		path: "",
		redirectTo: "/Main",
		pathMatch: "full"
	}
];
export const routing: ModuleWithProviders = RouterModule.forRoot(appRoutes);
export const declarations = [Main,DemoDemo0,DemoIndex];
